package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/goloop/pgc/internal/gen"
)

// generatedHeader is the first line of every file pgc writes. It is how a
// file in the output directory is recognised as pgc's own: only such a file
// is ever rewritten or removed, and hand-written code beside it never is.
const generatedHeader = "// Code generated by pgc. DO NOT EDIT."

// outputPlan is what bringing the output directory up to date takes.
type outputPlan struct {
	write []gen.OutFile // new or changed files
	stale []string      // files pgc wrote earlier that nothing produces now
}

// empty reports whether the directory is already up to date.
func (p outputPlan) empty() bool { return len(p.write) == 0 && len(p.stale) == 0 }

// planOutput compares the generated files with the directory. A file pgc
// generated earlier whose query file has since been deleted or renamed is
// stale: left in place it would keep an API, and its SQL, the queries no
// longer describe.
func planOutput(dir string, files []gen.OutFile) (outputPlan, error) {
	var plan outputPlan
	produced := map[string]bool{}
	for _, f := range files {
		produced[f.Name] = true
		old, err := os.ReadFile(filepath.Join(dir, f.Name))
		if err != nil && !os.IsNotExist(err) {
			return plan, err
		}
		if err != nil || !bytes.Equal(old, f.Data) {
			plan.write = append(plan.write, f)
		}
	}

	entries, err := os.ReadDir(dir)
	if err != nil && !os.IsNotExist(err) {
		return plan, err
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || produced[name] {
			continue
		}
		ours, err := isGenerated(filepath.Join(dir, name))
		if err != nil {
			return plan, err
		}
		if ours {
			plan.stale = append(plan.stale, name)
		}
	}
	sort.Strings(plan.stale)
	return plan, nil
}

// isGenerated reports whether a file starts with pgc's header.
func isGenerated(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	line, err := bufio.NewReader(f).ReadString('\n')
	if err != nil && line == "" {
		return false, nil
	}
	return strings.TrimRight(line, "\r\n") == generatedHeader, nil
}

// describe lists the plan for a message, one file per line.
func (p outputPlan) describe(dir string) string {
	var lines []string
	for _, f := range p.write {
		lines = append(lines, "  out of date: "+filepath.Join(dir, f.Name))
	}
	for _, name := range p.stale {
		lines = append(lines, "  stale:       "+filepath.Join(dir, name))
	}
	return strings.Join(lines, "\n")
}

// apply writes the plan. Each file is replaced atomically - written beside
// its destination and renamed over it - so an interrupted run leaves every
// file either as it was or as it should be, never cut short. Stale files go
// last, once everything that replaces them is in place.
func (p outputPlan) apply(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, f := range p.write {
		path := filepath.Join(dir, f.Name)
		if err := writeFileAtomic(path, f.Data, 0o644); err != nil {
			return err
		}
		fmt.Println(path)
	}
	for _, name := range p.stale {
		path := filepath.Join(dir, name)
		if err := os.Remove(path); err != nil {
			return err
		}
		fmt.Println("removed", path)
	}
	return nil
}

// writeFileAtomic replaces path with data in one rename.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // after a successful rename there is nothing to remove

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, perm); err != nil {
		return err
	}
	return os.Rename(name, path)
}
